### ISSUE TITLE
"missing_version" errors on Deploy

### ISSUE THREAD

**Issue by emzeidan** [heroku/heroku-bamboo-plugin#10]
Hi there,

I'm a Bamboo Support Engineer at Atlassian, and I received an issue today where a user is receiving the following error when running a Heroku task on Bamboo version 5.15.3:
> com.heroku.api.exception.RequestFailedException: Failed to create app statuscode:400 responseBody:{"id":"missing_version","error":"Please specify a version along with Heroku's API MIME type. For example, `Accept: application/vnd.heroku+json; version=3`.\n"}

Any tips or guidance would be appreciated!

Thanks in advance!

**Comment by jkutner** [comment]
@emzeidan thanks for the report. This plugin is deprecated, and uses an old version of the Heroku API that has been shut down. Please recommend to your users that they use one of the alternative deployment mechanisms described in [our DevCenter article on WAR deployment](https://devcenter.heroku.com/articles/war-deployment). If you can remove from the plugin from any Bamboo marketplace (or similar thing) that would be helpful too. Thanks.
